# Generated by Django 5.2.6 on 2025-10-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ("Jum'at", "Jum'at"), ('Sabtu', 'Sabtu'), ('Minggu', 'Minggu')], max_length=10)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Jadwal Pelajaran',
            },
        ),
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(db_index=True, max_length=255)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Jurusan',
            },
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Kelas',
            },
        ),
        migrations.CreateModel(
            name='KelasSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Pendaftaran Kelas Siswa',
            },
        ),
        migrations.CreateModel(
            name='Mapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Mata Pelajaran',
            },
        ),
        migrations.CreateModel(
            name='TahunAjaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.CharField(max_length=10)),
                ('semester', models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], max_length=10)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Tahun Ajaran',
            },
        ),
    ]
