# Generated by Django 5.2.7 on 2025-10-30 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwal',
            name='guru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.guru'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='jurusan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.jurusan'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='wali_kelas',
            field=models.ForeignKey(limit_choices_to={'akun__peran__nama': 'Guru'}, on_delete=django.db.models.deletion.PROTECT, related_name='kelas_diampu', to='users.guru'),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.kelas'),
        ),
        migrations.AddField(
            model_name='kelassiswa',
            name='kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.kelas'),
        ),
        migrations.AddField(
            model_name='kelassiswa',
            name='siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.siswa'),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='mapel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.mapel'),
        ),
        migrations.AddConstraint(
            model_name='tahunajaran',
            constraint=models.UniqueConstraint(fields=('tahun', 'semester'), name='unique_academic_period'),
        ),
        migrations.AddField(
            model_name='kelassiswa',
            name='tahun_ajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.tahunajaran'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='tahun_ajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.tahunajaran'),
        ),
        migrations.AddConstraint(
            model_name='jadwal',
            constraint=models.UniqueConstraint(fields=('kelas', 'hari', 'jam_mulai'), name='unique_class_schedule_time'),
        ),
        migrations.AddConstraint(
            model_name='jadwal',
            constraint=models.UniqueConstraint(fields=('guru', 'hari', 'jam_mulai'), name='unique_teacher_schedule_time'),
        ),
        migrations.AddIndex(
            model_name='kelassiswa',
            index=models.Index(fields=['kelas', 'tahun_ajaran'], name='academics_k_kelas_i_6272db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kelassiswa',
            unique_together={('siswa', 'kelas', 'tahun_ajaran')},
        ),
        migrations.AddConstraint(
            model_name='kelas',
            constraint=models.UniqueConstraint(fields=('nama', 'tahun_ajaran'), name='unique_class_period'),
        ),
    ]
