# Generated by Django 5.2.7 on 2025-11-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapel',
            name='nama',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
