# Generated by Django 5.2.6 on 2025-10-30 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Akun',
            },
        ),
        migrations.CreateModel(
            name='Peran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Peran Akun',
            },
        ),
        migrations.CreateModel(
            name='Wali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('tanggal_lahir', models.DateTimeField()),
                ('nomor_handphone', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default='L', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Wali Murid',
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('tanggal_lahir', models.DateTimeField()),
                ('nomor_handphone', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default='L', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nis', models.CharField(max_length=255, unique=True)),
                ('akun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='siswa_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Siswa',
            },
        ),
        migrations.AddField(
            model_name='akun',
            name='peran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.peran'),
        ),
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('tanggal_lahir', models.DateTimeField()),
                ('nomor_handphone', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default='L', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nip', models.CharField(max_length=255, unique=True)),
                ('jabatan', models.CharField(max_length=100)),
                ('akun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='guru_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Guru',
                'indexes': [models.Index(fields=['jabatan'], name='users_guru_jabatan_44c913_idx')],
            },
        ),
        migrations.CreateModel(
            name='SiswaWali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hubungan', models.CharField(choices=[('Ayah', 'Ayah'), ('Ibu', 'Ibu'), ('Wali', 'Wali')], max_length=10)),
                ('wali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.wali')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.siswa')),
            ],
            options={
                'verbose_name_plural': 'Hubungan Siswa-Wali',
                'indexes': [models.Index(fields=['wali', 'siswa'], name='users_siswa_wali_id_3840d5_idx')],
                'unique_together': {('siswa', 'wali')},
            },
        ),
    ]
