# Generated by Django 5.2.7 on 2025-10-30 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('Hadir', 'Hadir'), ('Sakit', 'Sakit'), ('Izin', 'Izin'), ('Alpha', 'Alpha')], max_length=10)),
                ('keterangan', models.TextField(blank=True, help_text="Penjelasan terkait status kehadiran selain 'Hadir'", null=True)),
            ],
            options={
                'verbose_name_plural': 'Presensi Siswa',
            },
        ),
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(db_index=True, max_length=255)),
                ('deskripsi', models.TextField()),
                ('mulai', models.DateTimeField()),
                ('tenggat', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Tugas',
            },
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_penilaian', models.CharField(choices=[('Tugas', 'Tugas'), ('Ujian Harian', 'Ujian Harian'), ('UTS', 'UTS'), ('UAS', 'UAS')], max_length=20)),
                ('nilai', models.DecimalField(db_index=True, decimal_places=2, max_digits=5)),
                ('tanggal_penilaian', models.DateField()),
                ('jadwal', models.ForeignKey(help_text='Konteks mapel/kelas/guru', on_delete=django.db.models.deletion.CASCADE, to='academics.jadwal')),
            ],
            options={
                'verbose_name_plural': 'Nilai Siswa',
            },
        ),
    ]
