# Generated by Django 5.2.7 on 2025-10-30 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('grades', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nilai',
            name='siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.siswa'),
        ),
        migrations.AddField(
            model_name='presensi',
            name='jadwal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.jadwal'),
        ),
        migrations.AddField(
            model_name='presensi',
            name='siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.siswa'),
        ),
        migrations.AddField(
            model_name='tugas',
            name='jadwal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.jadwal'),
        ),
        migrations.AddField(
            model_name='nilai',
            name='tugas',
            field=models.ForeignKey(blank=True, help_text='Isi jika tipe penilaian adalah Tugas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='grades.tugas'),
        ),
        migrations.AddIndex(
            model_name='presensi',
            index=models.Index(fields=['jadwal', 'tanggal'], name='grades_pres_jadwal__fd7a20_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='presensi',
            unique_together={('siswa', 'jadwal', 'tanggal')},
        ),
    ]
